apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.10.2
    helm:
      releaseName: loki
      values: |
        loki:
          isDefault: false
          config:
            table_manager:
              retention_deletes_enabled: true
              retention_period: 336h
            limits_config:
              retention_period: 336h
        promtail:
          enabled: true
    chart: loki-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
