apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  # This tells k3s to use your internal SSD (Performance Tier)
  storageClassName: local-path 
  resources:
    requests:
      storage: 5Gi
